export interface Permission {
  id: number;
  resource: string;
  action: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}

export enum PermissionEnum {
  // Sample Testcases
  SAMPLE_TESTCASE_CREATE = 1,
  SAMPLE_TESTCASE_READ = 2,
  SAMPLE_TESTCASE_UPDATE = 3,
  SAMPLE_TESTCASE_DELETE = 4,

  // Solutions
  SOLUTION_CREATE = 5,
  SOLUTION_READ = 6,
  SOLUTION_UPDATE = 7,
  SOLUTION_DELETE = 8,
  SOLUTION_VOTE = 9,

  // Solution Comments
  SOLUTION_COMMENT_CREATE = 10,
  SOLUTION_COMMENT_READ = 11,
  SOLUTION_COMMENT_UPDATE = 12,
  SOLUTION_COMMENT_DELETE = 13,
  SOLUTION_COMMENT_VOTE = 14,

  // Roles
  ROLE_CREATE = 15,
  ROLE_READ = 16,
  ROLE_UPDATE = 17,
  ROLE_DELETE = 18,

  // Problems
  PROBLEM_CREATE = 19,
  PROBLEM_READ = 20,
  PROBLEM_UPDATE = 21,
  PROBLEM_DELETE = 22,
  PROBLEM_READ_ALL = 23,

  // Submissions
  SUBMISSION_CREATE = 24,
  SUBMISSION_READ = 25,
  SUBMISSION_READ_ALL = 26,

  // Contests
  CONTEST_CREATE = 27,
  CONTEST_READ = 28,
  CONTEST_UPDATE = 29,
  CONTEST_DELETE = 30,
  CONTEST_JOIN = 31,
  CONTEST_JOIN_PREMIUM = 32,

  // Users
  USER_READ = 33,
  USER_UPDATE = 34,
  USER_BAN = 35,
  USER_DELETE = 36,

  // Admin
  ADMIN_ACCESS = 37,
  ADMIN_ROLES = 38,
  ADMIN_STATISTICS = 39,

  // AI Features
  AI_INTERVIEW = 40,
  AI_HINT = 41,
  AI_UNLIMITED = 42,

  // Posts
  POST_CREATE = 43,
  POST_UPDATE = 44,
  POST_DELETE = 45,

  // Comments
  COMMENT_READ = 46,
  COMMENT_CREATE = 47,
  COMMENT_UPDATE = 48,
  COMMENT_DELETE = 49,

  // Comment Reports
  COMMENT_REPORT_READ = 50,
  COMMENT_REPORT_UPDATE = 51,

  // Payments
  PAYMENT_CREATE = 52,

  // Languages
  LANGUAGE_CREATE = 53,
  LANGUAGE_READ = 54,
  LANGUAGE_UPDATE = 55,
  LANGUAGE_DELETE = 56,
  LANGUAGE_ACTIVATE = 57,
  LANGUAGE_DEACTIVATE = 58,

  // Study Plans
  STUDY_PLAN_CREATE = 59,
  STUDY_PLAN_READ = 60,
  STUDY_PLAN_UPDATE = 61,
  STUDY_PLAN_DELETE = 62,
}
